version: 2
jobs:
  deploy_master:
    docker:
      - image: circleci/node:12.8
    steps:
      - add_ssh_keys:
          fingerprints:
            - "be:0f:b6:60:30:3a:60:b9:8a:46:6a:da:35:b2:09:f7"
      - run:
          name : set answer 'yes' on git clone
          command: $ ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: clone green-turtle
          command: git clone https://github.com/basd4g/green-turtle.git
      - run:
          name: clone green-turtle-article
          command: git clone git@github.com:basd4g/green-turtle-article.git
      - run:
          name: mv articles
          command: rm -rf green-turtle/assets && mkdir -p green-turtle/assets/article && mv green-turtle-article/* green-turtle/assets/article
      - run:
          name: yarn install
          command: cd green-turtle && yarn install
      - run:
          name: yarn make
          command: yarn make
      - run:
          name: yarn deploy
          command: yarn deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  workflow:
    jobs:
      - deploy_master:
          filters:
            branches:
              only: master
